"""empty message

Revision ID: 85a0563f226f
Revises: 2c0d4f4eea27
Create Date: 2021-06-22 20:57:47.957028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85a0563f226f'
down_revision = '2c0d4f4eea27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stages', sa.Column('type', sa.SmallInteger(), nullable=True))
    op.create_index(op.f('ix_stages_type'), 'stages', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stages_type'), table_name='stages')
    op.drop_column('stages', 'type')
    # ### end Alembic commands ###
