"""token

Revision ID: dfeb2ecf542e
Revises: 4a83cbe22d6f
Create Date: 2021-06-23 01:27:34.862500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfeb2ecf542e'
down_revision = '4a83cbe22d6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
